"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { money, packageMoney } from "@/lib/format";
type College = { slug:string; name:string; city:string; state:string; annualFee:number; rating:number; courses:{name:string}[]; placements:{averagePackage:number|null;highestPackage:number|null;placementPercentage:number|null}[] };
const rows: { label: string; get: (college: College) => string }[] = [
  { label: "Location", get: c => `${c.city}, ${c.state}` }, { label: "Annual fee", get: c => money(c.annualFee) }, { label: "Rating", get: c => `★ ${c.rating.toFixed(1)}` },
  { label: "Average placement", get: c => packageMoney(c.placements[0]?.averagePackage) }, { label: "Highest placement", get: c => packageMoney(c.placements[0]?.highestPackage) }, { label: "Placement rate", get: c => c.placements[0]?.placementPercentage ? `${c.placements[0].placementPercentage}%` : "Not reported" }, { label: "Courses", get: c => c.courses.map(x => x.name).join(", ") }
];
export default function ComparePage({ searchParams }: { searchParams: Promise<{ ids?: string }> }) { const [ids,setIds]=useState<string[]>([]), [colleges,setColleges]=useState<College[]>([]), [error,setError]=useState(""); useEffect(()=>{ searchParams.then(p=> { const values=(p.ids??"").split(",").filter(Boolean); setIds(values); if(values.length>=2) fetch(`/api/colleges/compare?ids=${values.join(",")}`).then(r=>r.json().then(j=>({r,j}))).then(({r,j})=>r.ok?setColleges(j.data):setError(j.error.message)).catch(()=>setError("Unable to load comparison.")); });},[searchParams]); const remove=(id:string)=>{ setIds(v=>v.filter(x=>x!==id)); setColleges(v=>v.filter(x=>x.slug!==id)); }; if(error) return <main className="shell py-10"><h1 className="section-title">Compare colleges</h1><p className="mt-4 muted">{error}</p><Link className="btn btn-primary mt-4" href="/colleges">Explore colleges</Link></main>; if(ids.length<2) return <main className="shell py-10"><h1 className="section-title">Compare colleges</h1><div className="panel mt-5 p-10 text-center"><p className="font-bold">Choose two or three colleges to compare.</p><Link className="btn btn-primary mt-4" href="/colleges">Explore colleges</Link></div></main>; return <main className="shell py-8"><h1 className="section-title">Compare colleges</h1><p className="mt-1 muted">Decision factors side by side.</p><div className="panel mt-6 overflow-x-auto"><table className="min-w-[720px] w-full text-left text-sm"><thead><tr className="border-b border-line"><th className="p-4 text-slate-500">Attribute</th>{colleges.map(c=><th key={c.slug} className="min-w-52 p-4"><div className="flex justify-between gap-2"><Link href={`/colleges/${c.slug}`} className="font-bold text-brand">{c.name}</Link><button onClick={()=>remove(c.slug)} className="text-slate-500">×</button></div></th>)}</tr></thead><tbody>{rows.map(row=><tr className="border-b border-line" key={row.label}><th className="p-4 text-slate-500">{row.label}</th>{colleges.map(c=><td className="p-4" key={c.slug}>{row.get(c)}</td>)}</tr>)}</tbody></table></div></main>; }
