"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { CollegeCard } from "@/components/college-card";
type College = Parameters<typeof CollegeCard>[0]["college"];
export default function CollegesPage() { const [items, setItems] = useState<College[]>([]), [meta, setMeta] = useState({ page: 1, totalPages: 1, total: 0 }), [loading, setLoading] = useState(true), [error, setError] = useState(""), [compare, setCompare] = useState<string[]>([]); const [filters, setFilters] = useState({ search: "", state: "", type: "", minRating: "", sort: "rating_desc" });
 const load = async (page = 1) => { setLoading(true); setError(""); const p = new URLSearchParams({ page: String(page), limit: "9", sort: filters.sort }); Object.entries(filters).forEach(([k,v]) => { if (v && k !== "sort") p.set(k,v); }); try { const r = await fetch(`/api/colleges?${p}`); const json = await r.json(); if (!r.ok) throw new Error(json.error?.message); setItems(json.data); setMeta(json.meta); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load colleges."); } finally { setLoading(false); } };
 useEffect(() => { const timer = setTimeout(() => load(1), 250); return () => clearTimeout(timer); }, [filters]); const add = (id: string) => setCompare(current => current.includes(id) ? current : current.length === 3 ? current : [...current, id]);
 return <main className="shell py-8"><div className="mb-7"><h1 className="section-title">Explore colleges</h1><p className="mt-1 muted">Use filters to narrow a practical shortlist.</p></div><div className="grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="panel h-fit p-4"><h2 className="font-bold">Refine results</h2><div className="mt-4 space-y-3"><Field label="Search" value={filters.search} onChange={v => setFilters({...filters,search:v})} placeholder="College or location"/><Select label="State" value={filters.state} onChange={v => setFilters({...filters,state:v})} options={["Delhi","Tamil Nadu","Maharashtra","Karnataka","Uttar Pradesh"]}/><Select label="College type" value={filters.type} onChange={v => setFilters({...filters,type:v})} options={["GOVERNMENT","PRIVATE","DEEMED","AUTONOMOUS"]}/><Select label="Minimum rating" value={filters.minRating} onChange={v => setFilters({...filters,minRating:v})} options={["4","4.5"]}/><Select label="Sort by" value={filters.sort} onChange={v => setFilters({...filters,sort:v})} options={["rating_desc","fee_asc","fee_desc","name_asc"]}/><button className="btn btn-secondary w-full text-sm" onClick={() => setFilters({search:"",state:"",type:"",minRating:"",sort:"rating_desc"})}>Clear filters</button></div></aside><section><div className="mb-4 flex items-center justify-between text-sm muted"><span>{loading ? "Loading colleges…" : `${meta.total} colleges found`}</span>{compare.length > 0 && <Link href={`/compare?ids=${compare.join(",")}`} className="btn btn-primary text-sm">Compare {compare.length}</Link>}</div>{error ? <State title="Unable to load results" text={error} action={() => load(meta.page)}/> : loading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6].map(i => <div key={i} className="panel h-64 animate-pulse bg-slate-100"/>)}</div> : items.length ? <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(c => <CollegeCard key={c.slug} college={c} onCompare={add}/>)}</div><div className="mt-6 flex justify-center gap-3"><button className="btn btn-secondary disabled:opacity-40" disabled={meta.page===1} onClick={() => load(meta.page-1)}>Previous</button><span className="py-2 text-sm muted">Page {meta.page} of {meta.totalPages || 1}</span><button className="btn btn-secondary disabled:opacity-40" disabled={meta.page>=meta.totalPages} onClick={() => load(meta.page+1)}>Next</button></div></> : <State title="No colleges found" text="Try broadening your search or clearing one of the filters."/>}</section></div></main>; }
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}) { return <label className="label">{label}<input className="field mt-1 font-normal" value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>; }
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}) { return <label className="label">{label}<select className="field mt-1 font-normal" value={value} onChange={e=>onChange(e.target.value)}><option value="">Any</option>{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>; }
function State({title,text,action}:{title:string;text:string;action?:()=>void}) { return <div className="panel py-16 text-center"><h2 className="font-bold">{title}</h2><p className="mt-2 muted">{text}</p>{action && <button className="btn btn-primary mt-4" onClick={action}>Try again</button>}</div>; }
