import { CollegeType, ExamCode, PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
const schools = [
  ["Indian Institute of Technology", "Delhi", "Delhi", "GOVERNMENT"], ["National Institute of Technology", "Tiruchirappalli", "Tamil Nadu", "GOVERNMENT"], ["Birla Institute of Technology", "Pilani", "Rajasthan", "DEEMED"], ["Vellore Institute of Technology", "Vellore", "Tamil Nadu", "PRIVATE"], ["Manipal Institute of Technology", "Manipal", "Karnataka", "PRIVATE"], ["Delhi Technological University", "Delhi", "Delhi", "GOVERNMENT"], ["International Institute of Information Technology", "Bengaluru", "Karnataka", "AUTONOMOUS"], ["College of Engineering", "Pune", "Maharashtra", "GOVERNMENT"], ["Thapar Institute of Engineering", "Patiala", "Punjab", "PRIVATE"], ["Amity University", "Noida", "Uttar Pradesh", "PRIVATE"], ["National Institute of Technology", "Surathkal", "Karnataka", "GOVERNMENT"], ["Jamia Millia Islamia", "Delhi", "Delhi", "GOVERNMENT"]
] as const;
const suffixes = ["", " Institute of Technology", " School of Engineering", " University"];
async function main() {
  await prisma.review.deleteMany(); await prisma.cutoff.deleteMany(); await prisma.placement.deleteMany(); await prisma.course.deleteMany(); await prisma.college.deleteMany();
  for (let index = 0; index < 72; index++) { const [base, city, state, type] = schools[index % schools.length]; const campus = index < schools.length ? base : `${base}${suffixes[Math.floor(index / schools.length) % suffixes.length]} ${index + 1}`; const slug = campus.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); const annualFee = type === "GOVERNMENT" ? 45000 + (index % 5) * 18000 : 160000 + (index % 8) * 45000; const college = await prisma.college.create({ data: { slug, name: campus, city, state, address: `${city} Campus`, type: type as CollegeType, establishedYear: 1950 + (index % 65), description: `${campus} is a demonstration institution in the Campus Compass dataset. Its structured course, placement, review, and cutoff records are created for product evaluation and are not official information.`, annualFee, rating: Number((3.6 + (index % 14) / 10).toFixed(1)), ratingCount: 120 + index * 37, courses: { create: [{ name: "B.Tech Computer Science", degree: "B.Tech", durationMonths: 48, annualFee }, { name: "B.Tech Electronics", degree: "B.Tech", durationMonths: 48, annualFee: annualFee - 10000 }, { name: "MBA", degree: "MBA", durationMonths: 24, annualFee: annualFee + 60000 }] }, placements: { create: { year: 2025, averagePackage: 550000 + index * 35000, highestPackage: 1500000 + index * 120000, placementPercentage: 68 + (index % 27), recruiters: ["TCS", "Infosys", "Accenture", index % 2 ? "Deloitte" : "Amazon"] } }, reviews: { create: [{ displayName: "Aarav S.", rating: 4 + (index % 2) * .5, title: "Good academic environment", body: "The academic structure is practical and the campus offers useful opportunities for students who participate actively." }, { displayName: "Priya K.", rating: 3.5 + (index % 3) * .5, title: "Solid choice for the right course", body: "Faculty access and peer learning were strengths. Students should review the course-specific placement information carefully." }] } } }); const cutoff = 7000 + index * 1800; await prisma.cutoff.createMany({ data: [{ collegeId: college.id, exam: ExamCode.JEE_MAIN, year: 2025, openingRank: Math.max(1, cutoff - 4500), closingRank: cutoff }, { collegeId: college.id, exam: ExamCode.NEET_UG, year: 2025, openingRank: Math.max(1, cutoff - 3000), closingRank: cutoff + 8000 }, { collegeId: college.id, exam: ExamCode.CAT, year: 2025, openingRank: Math.max(1, cutoff - 2000), closingRank: cutoff + 4500 }] }); }
  console.log("Seeded 72 demo colleges.");
}
main().finally(() => prisma.$disconnect());
